# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inscriptions', '0014_auto_20160402_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='position_categorie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position catégorie'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='position_generale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position générale'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='temps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Temps (en secondes)'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='tours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de tours'),
        ),
    ]
