# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inscriptions', '0014_auto_20160402_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Texte'), ('list', 'Liste'), ('checkbox', 'Case à cocher')], max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('options', jsonfield.fields.JSONField()),
                ('attache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Rattaché à')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='inscriptions.Course')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='extra',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='position_categorie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position catégorie'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='position_generale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position générale'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='temps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Temps (en secondes)'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='tours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de tours'),
        ),
        migrations.AddField(
            model_name='equipier',
            name='extra',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
