# Generated by Django 2.0 on 2017-12-22 01:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inscriptions', '0028_auto_20171210_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Texte'), ('radio', 'Liste'), ('list', 'Liste déroulante'), ('checkbox', 'Case à cocher')], max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('options', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attache', models.ForeignKey(limit_choices_to={'app_label': 'inscriptions', 'model__in': ['Equipe', 'Equipier']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Rattaché à')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='inscriptions.Course')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='equipier',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='inscriptions.Course'),
        ),
    ]
