# Generated by Django 2.0 on 2017-12-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0030_auto_20171222_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraquestionchoice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
