# Generated by Django 2.0 on 2017-12-25 23:06

from django.db import migrations

CONNU_CHOICES = (
    'Site Roller en Ligne.com',
    'Facebook',
    'Presse',
    'Bouche à oreille',
    'Flyer pendant une course',
    'Flyer pendant une randonnée',
    'Affiche',
    'Informations de la Mairie',
    'Par mon club',
    'Autre',
)

TAILLES_CHOICES = (
    'XS',
    'S',
    'M',
    'L',
    'XL',
    'XXL',
)

# connu              = models.CharField(_('Comment avez vous connu la course ?'), max_length=200, choices=CONNU_CHOICES)
# transpondeur      = models.CharField(_(u'Transpondeur'), max_length=20, blank=True)
# taille_tshirt     = models.CharField(_(u'Taille T-shirt'), max_length=3, choices=TAILLES_CHOICES, blank=True)
def migrate_to_extra(apps, schema_editor):
    Equipe = apps.get_model('inscriptions', 'Equipe')
    Equipier = apps.get_model('inscriptions', 'Equipier')
    Course = apps.get_model('inscriptions', 'Course')
    ExtraQuestion = apps.get_model('inscriptions', 'ExtraQuestion')
    ExtraQuestionChoice = apps.get_model('inscriptions', 'ExtraQuestionChoice')
    for course in Course.objects.filter(date__year__lte=2017):
        question1 = ExtraQuestion(
            course=course,
            page="Equipe",
            type='list',
            label="Comment avez vous connu la course ?",
            required=True,
        )
        question1.save()
        for v in CONNU_CHOICES:
            ExtraQuestionChoice(
                question=question1,
                label=v,
            ).save()
        
        question2 = ExtraQuestion(
            course=course,
            page="Equipier",
            type='list',
            label="Taille T-shirt",
            required=False,
        )
        question2.save()
        for v in TAILLES_CHOICES:
            ExtraQuestionChoice(
                question=question2,
                label=v,
            ).save()
        
        question3 = ExtraQuestion(
            course=course,
            page="Equipier",
            type='list',
            label="Transpondeur",
            required=False,
        )
        question3.save()
        
        for equipe in course.equipe_set.all():
            equipe.extra = {
                'extra%s' % question1.id: equipe.connu,
            }
            equipe.save()
        for equipier in Equipier.objects.filter(equipe__course=course):
            equipier.extra = {
                'extra%s' % question2.id: equipier.transpondeur,
                'extra%s' % question3.id: equipier.taille_tshirt,
            }
            equipier.save()




class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0031_auto_20171222_0306'),
    ]

    operations = [
        migrations.RunPython(migrate_to_extra),
    ]
