# Generated by Django 2.0 on 2017-12-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0032_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='connu',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='taille_tshirt',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='transpondeur',
        ),
        migrations.RemoveField(
            model_name='extraquestionchoice',
            name='help_text',
        ),
        migrations.AlterField(
            model_name='extraquestionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='inscriptions.ExtraQuestion'),
        ),
    ]
