# Generated by Django 2.0 on 2018-01-07 19:42

from django.db import migrations
from datetime import date

def update_templates(apps, schema_editor):
    TemplateMail = apps.get_model('inscriptions', 'templatemail')
    for tm in TemplateMail.objects.filter(course__date__gt=date(2018, 1, 1), nom__in=("paiement", "inscription", "paiement_admin", "inscription_admin", "changement_numero", "changement_numero_admin", "change_request")):
        tm.message = '{%% include "mails/%s.html" %%}' % tm.nom
        tm.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0033_auto_20171226_0039'),
    ]

    operations = [
        migrations.RunPython(update_templates),
    ]
