# Generated by Django 2.0 on 2018-01-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0036_add_extra_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipier',
            name='autorisation_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='Autorisation parentale valide'),
        ),
        migrations.AddField(
            model_name='equipier',
            name='piece_jointe_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat ou licence valide'),
        ),
    ]
