# Generated by Django 2.0 on 2018-01-08 22:42

from django.db import migrations

def update(apps, schema_editor):
    Equipier = apps.get_model('inscriptions', 'equipier')
    for e in  Equipier.objects.all():
        if e.autorisation_valide != None:
            e.autorisation_detail = 'oui' if e.autorisation_valide else 'non'
        if e.piece_jointe_valide != None:
            e.piece_jointe_detail = 'oui' if e.piece_jointe_valide else 'non'
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0037_auto_20180108_2342'),
    ]

    operations = [
        migrations.RunPython(update),
    ]
