# Generated by Django 2.0 on 2018-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0037_add_extra_perm2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='gerant_pays',
            field=models.CharField(default='FR', max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='equipier',
            name='pays',
            field=models.CharField(default='FR', max_length=2, verbose_name='Pays'),
        ),
    ]
