# Generated by Django 2.0 on 2018-01-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0038_valide_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipier',
            name='autorisation_valide',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='piece_jointe_valide',
        ),
    ]
