# Generated by Django 2.0 on 2018-02-18 18:32

from django.db import migrations

def create_facture_templates(apps, schema_editor):
    Course = apps.get_model('inscriptions', 'Course')
    TemplateMail = apps.get_model('inscriptions', 'TemplateMail')
    factures = TemplateMail.objects.filter(nom='facture')
    for course in Course.objects.exclude(id__in=(f.course.id for f in factures)):
        TemplateMail(
            course=course,
            nom='facture',
            destinataire='Equipe',
            sujet='Facture {{ instance.course.uid }}-{{ instance.numero }}',
            message='{% include "mails/facture.html" %}',
        ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0038_auto_20180112_2310'),
    ]

    operations = [
        migrations.RunPython(create_facture_templates),
    ]
