# Generated by Django 2.0 on 2018-05-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0039_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('espèce', 'espèce'), ('chèque', 'chèque'), ('paypal', 'paypal'), ('virement', 'virement'), ('autre', 'autre')], max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=7)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaiementRepartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=7)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inscriptions.Equipe')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='inscriptions.Paiement')),
            ],
        ),
    ]
