# Generated by Django 2.0 on 2018-01-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0039_auto_20180108_2357'),
        ('inscriptions', '0038_auto_20180112_2310'),
    ]

    operations = [
    ]
