# Generated by Django 2.0 on 2018-05-25 01:43

from django.db import migrations

def create_paiements(apps, schema_editor):
    Equipe = apps.get_model('inscriptions', 'Equipe')
    Paiement = apps.get_model('inscriptions', 'Paiement')
    PaiementRepartition = apps.get_model('inscriptions', 'PaiementRepartition')

    for e in Equipe.objects.filter(paiement__gt=0):
        p = Paiement(
            type='paypal' if 'Paypal' in e.paiement_info else 'chèque',
            montant=e.paiement,
            detail=e.paiement_info,
        )
        p.save()
        p.equipes.create(
            equipe=e,
            montant=e.paiement,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0040_paiement_paiementrepartition'),
    ]

    operations = [
        migrations.RunPython(create_paiements),
    ]
