# Generated by Django 2.0 on 2018-07-09 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0040_challenge_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationEquipier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=200, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('num_licence', models.CharField(blank=True, max_length=15, verbose_name='Numéro de licence')),
                ('equipiers', models.ManyToManyField(related_name='particpations', to='inscriptions.Equipier')),
            ],
        ),
        migrations.AddField(
            model_name='participationchallenge',
            name='nom',
            field=models.CharField(default='', max_length=30, verbose_name="Nom d'équipe"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participationequipier',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipiers', to='inscriptions.ParticipationChallenge'),
        ),
    ]
