# Generated by Django 2.0 on 2018-07-09 21:19

from django.db import migrations

def populate_participation_nom(apps, schema_editor):
    ParticipationChallenge = apps.get_model('inscriptions', 'ParticipationChallenge')
    for p in ParticipationChallenge.objects.prefetch_related('equipes__equipe'):
        if p.equipes.count():
            p.nom = p.equipes.all()[0].equipe.nom
            p.save()



class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0041_auto_20180709_2318'),
    ]

    operations = [
        migrations.RunPython(populate_participation_nom),
    ]
