# Generated by Django 2.0 on 2018-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0042_auto_20180709_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='verrou',
            field=models.BooleanField(default=False, verbose_name='Verrouillé'),
        ),
    ]
