# Generated by Django 2.0 on 2018-10-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0042_auto_20180709_2319'),
        ('inscriptions', '0041_paiements'),
    ]

    operations = [
    ]
