# Generated by Django 2.0 on 2018-10-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0043_merge_20181025_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='paiement_info',
        ),
    ]
