# Generated by Django 2.0 on 2018-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0044_remove_equipe_paiement_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='frais_stripe_inclus',
            field=models.BooleanField(default=False, verbose_name='Frais stripe inclus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_public',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Public Key'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
