# Generated by Django 2.0 on 2018-11-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0045_auto_20181124_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='paiement',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('espèce', 'espèce'), ('chèque', 'chèque'), ('paypal', 'paypal'), ('stripe', 'stripe'), ('virement', 'virement'), ('autre', 'autre')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paiementrepartition',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
