# Generated by Django 2.0 on 2018-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0046_auto_20181125_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Secret Key'),
        ),
    ]
