# Generated by Django 2.0 on 2019-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0047_course_stripe_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_frais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='paiementrepartition',
            name='montant_frais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
