# Generated by Django 2.0 on 2019-01-30 14:43

from django.db import migrations

def fix_templates(apps, schema_editor):
    Course = apps.get_model('inscriptions', 'Course')
    TemplateMail = apps.get_model('inscriptions', 'TemplateMail')
    for tpl in TemplateMail.objects.filter(
        nom='changement_numero_admin', 
        message="{% include \"mail/changement_numero_admin.html\" %}",
    ):
        tpl.message = "{% include \"mails/changement_numero_admin.html\" %}"
        tpl.save()

    TemplateMail.objects.filter(nom='facture', course__date__year=2019).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0048_auto_20190105_2315'),
    ]

    operations = [
        migrations.RunPython(fix_templates),
    ]
