# Generated by Django 2.0 on 2019-01-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0048_auto_20190105_2315'),
        ('inscriptions', '0043_equipier_cerfa_valide'),
    ]

    operations = [
    ]
