# Generated by Django 2.0 on 2019-01-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0049_merge_20190130_2239'),
        ('inscriptions', '0049_fix_templates'),
    ]

    operations = [
    ]
