# Generated by Django 2.0 on 2019-01-31 19:54

from django.db import migrations

def fix_templates(apps, schema_editor):
    Course = apps.get_model('inscriptions', 'Course')
    TemplateMail = apps.get_model('inscriptions', 'TemplateMail')
    TemplateMail.objects.filter(nom='paiement_admin', course__date__year=2019).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0051_auto_20190131_2038'),
    ]

    operations = [
        migrations.RunPython(fix_templates),
    ]
