# Generated by Django 2.0 on 2019-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0052_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemail',
            name='destinataire',
            field=models.CharField(choices=[('Equipe', "Gerant d'équipe"), ('Equipier', 'Equipier'), ('Organisateur', 'Organisateur'), ('Tous', 'Tous')], max_length=20, verbose_name='Destinataire'),
        ),
    ]
