# Generated by Django 2.0 on 2019-03-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0053_auto_20190211_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=16)),
                ('up', models.BooleanField()),
                ('ip', models.CharField(max_length=50)),
                ('ua', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Equipe')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('equipe', 'cookie')},
        ),
    ]
