# Generated by Django 2.0 on 2019-04-27 13:14

from django.db import migrations
from pathlib import Path
from django.conf import settings

def move_uploads(apps, schema_editor):
    root = Path(settings.MEDIA_ROOT)
    Equipier = apps.get_model('inscriptions', 'Equipier')
    for equipier in Equipier.objects.all():
        dest = root / ('course_%d' % equipier.equipe.course_id) / ('equipe_%s_%s' % (equipier.equipe.id, equipier.equipe.password))
        dest.mkdir(parents=True, exist_ok=True)
        if equipier.piece_jointe:
            pj = root / equipier.piece_jointe.name
            if pj.exists():
                new_pj = dest / ('%s_%s%s' % (equipier.justificatif, equipier.numero, pj.suffix))
                print(pj, ' -> ', new_pj)
                pj.rename(new_pj)
                equipier.piece_jointe.name = str(new_pj.relative_to(root))
        if equipier.autorisation:
            pj = root / equipier.autorisation.name
            if pj.exists():
                new_pj = dest / ('autorisation_%s%s' % (equipier.numero, pj.suffix))
                print(pj, ' -> ', new_pj)
                pj.rename(new_pj)
                equipier.autorisation.name = str(new_pj.relative_to(root))
        equipier.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0053_auto_20190211_1342'),
    ]

    operations = [
        migrations.RunPython(move_uploads),
    ]
