# Generated by Django 2.0 on 2019-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0054_auto_20190331_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='cookie',
            field=models.CharField(max_length=40),
        ),
    ]
