# Generated by Django 2.0 on 2019-07-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0055_auto_20190703_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='stripe_intent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
