# Generated by Django 2.0 on 2019-07-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0043_equipe_verrou'),
        ('inscriptions', '0055_auto_20190703_2325'),
    ]

    operations = [
    ]
