# Generated by Django 2.0 on 2019-07-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0056_paiement_stripe_intent'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE inscriptions_paiement DROP COLUMN IF EXISTS stripe_charge_id"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_account CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_bankaccount CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_bitcoinreceiver CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_card CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_charge CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_coupon CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_customer CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_event CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_eventprocessingexception CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_invoice CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_invoiceitem CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_plan CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_subscription CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_transfer CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_transferchargefee CASCADE"),
        migrations.RunSQL("DROP TABLE IF EXISTS pinax_stripe_useraccount CASCADE"),
    ]
