# Generated by Django 2.0 on 2019-08-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0056_merge_20190706_1406'),
        ('inscriptions', '0058_course_stripe_endpoint_secret'),
    ]

    operations = [
    ]
