# Generated by Django 2.0 on 2019-12-01 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0059_merge_20190815_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='prix1',
            new_name='prix_base1',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='prix2',
            new_name='prix_base2',
        ),
        migrations.AddField(
            model_name='categorie',
            name='prix_equipier1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Prix normal'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='prix_equipier2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Prix augmenté'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='verrou',
            field=models.BooleanField(default=False, verbose_name="Equipe verrouillée (modifiable uniquement par l'organisateur)"),
        ),
    ]
