# Generated by Django 2.0 on 2020-02-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0060_auto_20191201_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='ajouter_nombre',
            field=models.BooleanField(default=False, verbose_name="Numero de dossard (ajouter le nombre d'équipiers)"),
        ),
    ]
