# Generated by Django 2.0 on 2021-09-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0060_auto_20210904_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='course',
            name='texte_accueil',
            field=models.TextField(blank=True, null=True, verbose_name="Texte d'accueil"),
        ),
    ]
