# Generated by Django 2.0 on 2020-02-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0059_merge_20190709_1447'),
        ('inscriptions', '0061_categorie_ajouter_nombre'),
    ]

    operations = [
    ]
