# Generated by Django 2.0 on 2022-02-04 21:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0061_auto_20210904_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], upload_to='logo', verbose_name='Logo'),
        ),
    ]
