# Generated by Django 2.0 on 2022-04-04 12:51

from django.db import migrations

def add_perm(apps, schema_editor):
    User = apps.get_model('auth', 'user')
    Permission = apps.get_model('auth', 'permission')
    for perm in  Permission.objects.filter(codename__in=('add_paiement', 'change_paiement', 'delete_paiement', 'add_paiementrepartition', 'change_paiementrepartition', 'delete_paiementrepartition')):
        for user in User.objects.exclude(user_permissions=perm):
            user.user_permissions.add(perm)

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0063_course_date_age'),
    ]

    operations = [
        migrations.RunPython(add_perm),
    ]
