# Generated by Django 2.0 on 2024-09-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0063_course_date_age'),
        ('inscriptions', '0054_uploads'),
    ]

    operations = [
    ]
