# Generated by Django 2.0 on 2024-09-23 16:42

from django.db import migrations, models
import django_resized.forms
import inscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0064_merge_20240917_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_age',
            field=models.DateField(blank=True, default=None, help_text='Date à utiliser pour le calcul des ages. Laisser vide pour utiliser la date de la course', null=True, verbose_name='Date calcul ages'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=False, null=True, quality=85, scale=None, size=[600, 600], upload_to='logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='equipier',
            name='autorisation',
            field=models.FileField(blank=True, help_text="Si vous le pouvez, scannez l'autorisation et ajoutez la en pièce jointe (formats PDF ou JPEG).\nVous pourrez aussi la télécharger plus tard, ou l'envoyer par courrier (%(link)s)", upload_to=inscriptions.models.equipier_autorisation_filename, verbose_name='Autorisation parentale'),
        ),
        migrations.AlterField(
            model_name='equipier',
            name='piece_jointe',
            field=models.FileField(blank=True, upload_to=inscriptions.models.equipier_piece_jointe_filename, verbose_name='Certificat ou licence'),
        ),
    ]
