# Generated by Django 2.0 on 2024-09-23 17:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0065_auto_20240923_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='dates_augmentation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(verbose_name="Date d'augmentation des tarifs"), default=[], size=None),
        ),
        migrations.AddField(
            model_name='extraquestion',
            name='prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix'), default=[], size=None),
        ),
        migrations.AddField(
            model_name='extraquestionchoice',
            name='prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix augmenté'), default=[], size=None),
        ),
    ]
