# Generated by Django 2.0 on 2024-10-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0068_auto_20240923_2051'),
        ('inscriptions', '0066_add_paiement_perm2'),
    ]

    operations = [
    ]
