# Generated by Django 2.0 on 2025-02-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0070_auto_20241003_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('espèce', 'espèce'), ('chèque', 'chèque'), ('paypal', 'paypal'), ('stripe', 'stripe'), ('virement', 'virement'), ('offert', 'offert'), ('autre', 'autre')], max_length=200),
        ),
    ]
