# Generated by Django 2.0 on 2025-02-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0071_auto_20250204_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='stripe_intent',
            new_name='intent_id',
        ),
        migrations.AddField(
            model_name='course',
            name='helloasso_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='HelloAsso clientId'),
        ),
        migrations.AddField(
            model_name='course',
            name='helloasso_organisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='HelloAsso organization name'),
        ),
        migrations.AddField(
            model_name='course',
            name='helloasso_sandbox',
            field=models.BooleanField(default=False, verbose_name='HelloAsso sandbox'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='helloasso_secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='HelloAsso clientSecret'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(choices=[('espèce', 'espèce'), ('chèque', 'chèque'), ('paypal', 'paypal'), ('stripe', 'stripe'), ('helloasso', 'helloasso'), ('virement', 'virement'), ('offert', 'offert'), ('autre', 'autre')], max_length=200),
        ),
    ]
