# Generated by Django 2.0 on 2025-02-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0072_auto_20250206_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='gerant_adress2',
            new_name='gerant_adresse2',
        ),
    ]
