# Generated by Django 2.0 on 2025-08-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0073_auto_20250207_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('equipier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='inscriptions.Equipier')),
            ],
        ),
    ]
