# Generated by Django 2.0 on 2025-08-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0074_tours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tours',
            new_name='Tour',
        ),
    ]
