# Generated by Django 2.0 on 2025-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0075_auto_20250806_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duree',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Duree (en secondes)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='timestamp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Heure (en secondes)'),
        ),
    ]
