# Generated by Django 2.0 on 2026-01-31 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0076_auto_20250806_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='prices',
            new_name='prices_base',
        ),
        migrations.AddField(
            model_name='categorie',
            name='ajouter_nombre',
            field=models.BooleanField(default=False, verbose_name="Numero de dossard (ajouter le nombre d'équipiers)"),
        ),
        migrations.AddField(
            model_name='categorie',
            name='prices_equipier',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), default=[], size=None, verbose_name='Prix par équipier'),
        ),
    ]
