# Generated by Django 2.0 on 2026-02-08 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0077_auto_20260131_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='prices_base',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), default=[], size=None, verbose_name='Prix de base'),
        ),
    ]
