# Generated by Django 2.0 on 2026-02-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0078_auto_20260208_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipier',
            name='adresse1',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='adresse2',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='equipier',
            name='ville2',
        ),
    ]
