# Generated by Django 2.0 on 2026-02-25 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0079_auto_20260208_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dates_augmentation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=[], null=True, size=None, verbose_name="Date d'augmentation des tarifs"),
        ),
    ]
