# Generated by Django 2.0 on 2026-02-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0079_auto_20260208_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseEdition',
        ),
    ]
