# Generated by Django 2.0 on 2026-02-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0079_auto_20260209_0101'),
        ('inscriptions', '0079_auto_20260208_1818'),
    ]

    operations = [
    ]
