# Generated by Django 2.0 on 2026-02-08 23:15

from django.db import migrations

def change_perms(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    for p in Permission.objects.filter(codename__endswith='_course'):
        print(p.codename)
        p.codename = p.codename.replace('_course', '_courseedition');
        p.name = p.name.replace('course', 'course edition')
        p.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0080_auto_20260208_2148'),
    ]

    operations = [
        migrations.RunPython(change_perms),
    ]
