# Generated by Django 2.0 on 2026-02-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0080_auto_20260225_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delai_paiement',
            field=models.IntegerField(default=31, help_text='En jours. Ce délai est affiché purement à titre indicatif. La suppression devra être faite manuellement (ou pas).', verbose_name='Délai de paiement avant annulation'),
        ),
    ]
