# Generated by Django 2.0 on 2026-04-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0081_course_delai_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lien_externe',
            field=models.URLField(blank=True, null=True, verbose_name='Lien inscription externe'),
        ),
    ]
