# Generated by Django 2.0 on 2026-02-08 21:52

from django.db import migrations
from collections import defaultdict
import re

def group_courses(apps, schema_editor):
    Course = apps.get_model("inscriptions", "Course")
    CourseEdition = apps.get_model("inscriptions", "CourseEdition")

    groups = defaultdict(lambda: [])
    groups_uid = {}

    for c in CourseEdition.objects.order_by('-date'):
        ville = re.sub('st ', 'saint ', c.ville.lower().replace('-', ' '))
        uid = re.sub(' *\d+$', '', c.uid)
        if uid in groups_uid:
            groups_uid[uid].append(c)
        else:
            groups[ville].append(c)
            groups_uid[uid] = groups[ville]

    print(groups.keys())
    for group in groups.values():
        args = { k: getattr(group[0], k) for k in ('nom', 'uid', 'organisateur', 'ville', 'url', 'logo', 'paypal', 'frais_paypal_inclus', 'stripe_secret', 'stripe_public', 'stripe_endpoint_secret', 'frais_stripe_inclus', 'helloasso_organisation', 'helloasso_id', 'helloasso_secret', 'helloasso_sandbox', 'ordre', 'adresse',)}
        args['active'] = True
        args['nom'] = re.sub(' *\d+$', '', group[0].nom)
        args['uid'] = re.sub(' *\d+$', '', group[0].uid)
        course = Course(**args)
        course.save()
        print('course', course)
        for edition in group:
            edition.course = course
            edition.save()
            print('edition', edition)
    from django.db import connection
    print(connection.queries)

class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0082_auto_20260209_0027'),
    ]

    operations = [
        migrations.RunPython(group_courses),
    ]
